CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS ai CASCADE;
-- CREATE EXTENSION IF NOT EXISTS vectorscale;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CREATE EXTENSION IF NOT EXISTS ai cascade;
-- CREATE EXTENSION IF NOT EXISTS vectorscale cascade;
