version: '3.7'

services:
  postgres:
    container_name: figtech_db
    image: timescale/timescaledb-ha:pg17
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: figtech_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/migrations/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ../db/migrations/02-init-extensions.sql:/docker-entrypoint-initdb.d/02-init-extensions.sql
      - ../db/migrations/03-init-tables.sql:/docker-entrypoint-initdb.d/03-init-tables.sql
    ports:
      - '5440:5432'
    networks:
      - postgres

  pgadmin:
    container_name: figtech_db_admin
    image: dpage/pgadmin4:9.4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/.data/pgadmin
    ports:
      - '53610:80'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
